### ISSUE TITLE
Run at startup with a local database path causes the database to not be able to sync

### ISSUE THREAD

**Issue by Agendum** [KoenZomers/KeePassOneDriveSync#71] opened 2018-11-26 20:16 UTC
I use a local database path in my app and KeeOneDrive configuration because I copy this configuration to multiple devices. In the Application Path section it is "Database\KeePass.kdbx" and in the KeeOneDrive section the path is "Database\\KeePass.kdbx".

Everything normally works. I can sync the database, close the app, open the app, etc. However, in KeePass if I enable "Options > Run KeePass at Windows startup (current user)" the KeePassOneDriveSync is no longer able to synchronize the file. What happens is the user logs into Windows, KeePass starts, I enter my credentials, and KeePassOneDriveSync attempts to sync. However it fails, and the following error is in the status bar:

Failed to sync database: Could not find a part of the path 'C:\windows\system32\Database\KeePass.kdbx'

By using ProcessExplorer, I see the difference is the working directory. When I manually start KeePass.exe, the working directory is C:\KeePass, but when I use autostart, the working directory is C:\WINDOWS\System32. I tested this is the problem by making a shortcut and set the start directory to be C:\WINDOWS\System32 and I was able to reproduce the problem outside of autostart.

All of this means is that currently KeePassOneDriveSync cannot be used with autostart and local files paths.

**Comment by drujd** [comment] 2018-12-03 13:31
This is not really a bug. Relative path is relative to working directory. If you set up Task Scheduler to run KeePass after login, you can set working dir to whatever you want and it will work.

**Comment by KoenZomers** [comment] 2018-12-03 13:49
I agree with @drujd here. It just takes the path relative to the execution path of KeePass.exe. If the KeePass database is not stored under the path where KeePass.exe resides, then it will store the full path to the database and then theoretically it should still work if KeePass.exe gets executed from the c:\windows\system32 context. Can you give this a try?

**Comment by Agendum** [comment] 2018-12-03 18:02
I believe @drujd is correct, but @KoenZomers I don't believe what you said is correct. There are two options here:

1) The application is started with a current working directory (Directory.GetCurrentDirectory and Directory.SetCurrentDirectory in .NET). This appears to be what KeePassOneDriveSync is using to resolve the relative path to the database.
2) Begin the relative path from the location where KeePass.exe resides. In .NET this would be Assembly.GetEntryAssembly().Location.

@KoenZomers it sounds like you describe #2 while @drujd describes #1. Right now the behavior of KeePassOneDriveSync is #1 as I demonstrated in my first post. I could do a lot of things to overcome this, like use Task Scheduler, a batch file with auto run, etc. But those options do not achieve the modular behavior KeePass allows.

I consider this a bug and not a feature request because KeePassOneDriveSync resolves the relative path to the database differently than KeePass.exe itself. For example, in my configuration Configuration\Application\LastUsedFile\Path, Configuration\Defaults\KeySources\Association\DatabasePath, and Configuration\Custom\Item(KeeOneDrive)\Value all set the path to be Database\KeePass.kdbx. Even with an invalid current working directory KeePass.exe itself is able to load my database, but KeePassOneDriveSync cannot. This tells me that KeePass.exe is using #2 to resolve relative paths and that KeePassOneDriveSync is using an inconsistent method (#1) to resolve relative paths.

At the very least, provide an option in KeeOneDrive configuration to resolve the relative path the same way KeePass.exe does.

**Comment by Agendum** [comment] 2019-02-16 19:22
Almost 3 months have gone by and this issue is still flagged with "waiting for more information". There doesn't seem to be a way to change the state to bring awareness. Can I get confirmation that you have enough information? I have addressed all statements, and provided plenty of information on the issue, what causes it, and how to repro. If this won't be fixed, that's fine (and unfortunate), but I need clarification that resolving this problem is not be blocked on information (or lack thereof) I provided. Thanks!

**Comment by KoenZomers** [comment] 2019-02-17 20:42
@Agendum, your point is clear and the information you have provided helped me to understand what you mean. Limiting factor here is my spare time. I've got quite a few open source projects I'm active in and the issues and feature requests reported on GitHub are just a small fraction of what I receive through other channels as well. Each reported item easily takes a few hours to reproduce/investigate/implement/test. You're the first and up till now only one reporting this, so it gets less of a priority than something that several people report. You have a fair point in that the behavior of the file location deviates from how KeePass handles it itself. I've given it some thoughts and it would require quite a bit of rework and extensive testing of the code as it would impact a lot of things and backwards compatibility would need to be maintained. I don't like to go for an advanced settings kind of option where someone can choose to go with absolute or relative paths. That gets things messy and hard to understand plus implementing that properly would be even more of a challenge. For now I'll consider it as an improvment request with in all honesty less priority. If time permits me, I will see if I can implement this.

**Comment by Agendum** [comment] 2019-02-17 20:57
I understand. All of us thank you for giving us your time to make us this great plugin. Thanks for updating the state of the issue.

**Comment by brano-p** [comment] 2019-04-11 09:25
I have experienced the same symptoms (_Failed to sync database: Could not find a part of the path 'C:\windows\system32\Database\<whatever>.kdbx'_). However, currently (KP 2V.4.1 with OneDrive Sync V2.0.2.5) it miraculously disappeared and the sync worked flawlessly. I'll try to sync on my other machine and see and investigate deeper if it's still the case.

**Comment by KoenZomers** [comment] 2019-04-11 13:03
I haven't done any work in this area, so it would be something else if it indeed has been resolved.

**Comment by Agendum** [comment] 2019-04-11 15:52
I can confirm the issue still exists with the latest version. @brano-p maybe your databases were in sync when you started KeePass - try clicking Save and see if you get the error.

**Comment by brano-p** [comment] 2019-04-11 16:28
@Agendum they were not in sync, I have changed and saved the database to see if the sync has been performed.
I've just tested the sync again on my other machine (at home) and it worked flawlessly.
I really don't know why, because I was struggling with it for several months with the same issue! 
History: I've tried everything, even changing the database location (on my OneDrive, this helped someone with a different issue) and nothing helped so after trying many times, reinstalling, etc., I've just resigned. Yesterday and today I've tried again **without changing anything** on both machines (work & home) and it just works. I'm really clueless.

**Comment by Agendum** [comment] 2019-04-11 16:34
@brano-p, strange. My only thoughts are:
1) Maybe your database is actually relative under your C:\windows\system32 folder and therefore the plugin can find it.
2) Maybe the way your KeePass is auto-started it is inheriting the current working directory correctly instead of defaulting to C:\windows\system32.
3) Maybe you actually didn't even auto-start KeePass using the configured integration option, and are auto-starting it a different way? Or maybe it didn't even auto-start at all and you mistakenly manually started it? Try quitting KeePass, rebooting, and seeing how auto-start launches it.

**Comment by brano-p** [comment] 2019-04-11 16:39
@Agendum I'm sorry - now I see what's the problem, I have to backpedal with my observations. I can confirm the behavior: if KeePass has been launched at startup (with the checkbox in KeePass configuration), it really looks under  C:\windows\system32.
When I've closed it and launched again manually, then it works correctly. I'll try to use other means to run it at start ("Startup folder") where I can specify the working folder explicitly.

**Comment by brano-p** [comment] 2019-04-11 16:39
@Agendum I'm sorry - now I see what's the problem, I have to backpedal with my observations. I can confirm the behavior: if KeePass has been launched at startup (with the checkbox in KeePass configuration), it really looks under  C:\windows\system32.
When I've closed it and launched again manually, then it works correctly. I'll try to use other means to run it at start ("Startup folder") where I can specify the working folder explicitly.

**Comment by KoenZomers** [comment] 2020-05-16 08:05
I believe this issue has been resolved with the merge of the PR. Therefore closing is. If you believe it hasn't been fixed yet, please let me know so we can reopen it again.

**Closed by KoenZomers** 2020-05-16 08:05 UTC
Labels: enhancement
