### ISSUE TITLE
Failed to Sync

### ISSUE THREAD

**Issue by DazzaQLD** [KoenZomers/KeePassOneDriveSync#26] opened 2016-12-22 12:27 UTC
Hi
I'm using the new v1.8.0.0 with v2.34 of KeePass on Windows 10 [Version 10.0.14393]. I'm syncing with OneDrive consumer. I'm running KeePass from a USB drive, D:\, and I'm using the .dll files for the plugin as per below.

Everytime I save my database it states 'Downloading KeePass database from OneDrive' but then reports 'Failed to sync. Please don't switch to another database before done'

I have removed the OneDrive sync configuration, setup a new sync, as in

- This KeePass database is not being synced with OneDrive. Would you like to set up a synchronization connection now? Yes, click OK
- Choose the cloud service you wish to store the KeePass database on: OneDrive
- Sign into my OneDrive
- Let this app access your info? Click Yes
- Where should KeeOneDriveSync store the OneDrive Refresh Token so it can keep your local database in sync with its equivallent on OneDrive? In the KeePass database itself, click Finish
- Select Location: /drive/root:/USB/KeePass/filename.kdbx. Click OK

Then it states 'Database does not exist....'
Then reports 'Successfully uploaded the new KeePass database to OneDrive'

I have verified the new file is on my OneDrive. If I then save my KeePass database again I get the same issue reported above, 'Failed to sync......'

The only other KeePass plugin I have loaded is KeePassHttp v1.8.4.1

OneDriveSync plugin files and versions

FileName                                                                                                       FileVersion
--------                                                                                                          -----------
D:\KeePass\Plugins\OneDriveSync\CredentialManagement.dll                    1.0.2
D:\KeePass\Plugins\OneDriveSync\KoenZomers.OneDrive.Api.dll                1.6.6.1
D:\KeePass\Plugins\OneDriveSync\KoenZomersKeePassOneDriveSync.dll  1.8.0.0
D:\KeePass\Plugins\OneDriveSync\Newtonsoft.Json.dll                               8.0.3.19514 

Regards
Daz

**Comment by KoenZomers** [comment] 2016-12-22 13:47
Hi Daz

Interesting find. I think I know what's going on already. In the last update I built in an extra check to avoid multiple databases getting synced to each other. I suspect for you it's using a relative path to the KeePass database location, right? To confirm, can you try storing the KeePass database in a folder lower that the folder in which you have the KeePass executable? My guess is that it will work then.

If you can do this test and let me know the outcome, I'll try to fix it.

**Comment by DazzaQLD** [comment] 2016-12-22 19:31
Hi

I've moved my KeePass database to a /db/ subfolder under the KeePass executables folder. I setup the OneDrive sync again. However, I still get the same result. The initial upload completes successfully but any subsequent saves and it reports 'Failed to sync....'

Cheers
Daz

**Comment by KoenZomers** [comment] 2016-12-22 20:22
Dont go for a folder in our under the folder where the KeePass executable resides. Either pick a different drive or a different folder above the KeePass folder. Just for testing this.

**Comment by DazzaQLD** [comment] 2016-12-23 06:48
Hi

Moved the /db folder to the root of the USB drive and yes that fixed this issue.
Great plugin by the way

Cheers
Daz

**Comment by KoenZomers** [comment] 2016-12-23 10:12
Thanks for confirming. Then I know what the issue is and will fix it in the next release :)

**Comment by KoenZomers** [comment] 2016-12-24 01:37
Fixed in 1.8.1.0

**Closed by KoenZomers** 2016-12-24 01:37 UTC
