### ISSUE TITLE
Plugin asks to setup synchronization even when 'never ask again' was selected

### ISSUE THREAD

**Issue by mushak** [KoenZomers/KeePassOneDriveSync#13] opened 2016-03-03 08:36 UTC
When I open a database file that isn't synchronized with OneDrive, the plugin asks me if I want to start synchronizing it. It gives me three options such as 'Yes', 'Not now' and 'No and never ask me again'. Despite of selecting 'Never ask again' the plugin will keep asking over and over again each time KeePass is restarted.

**Comment by KoenZomers** [comment] 2016-03-03 08:56
That's strange. Haven't seen this yet. Can you open up the following file on your PC using notepad:

C:\Users\<yourusername>\AppData\Roaming\KeePass\KeePass.config.xml

Scroll to the bottom and look for a section like:

`<Custom>
		<Item>
			<Key>KeeOneDrive</Key>
			<Value>{"C:\\<database location>.kdbx":{"RefreshToken":null,"RefreshTokenStorage":1,"OneDriveName":"<your name>","RemoteDatabasePath":"<remote path>.kdbx","DoNotSync":false,"LocalFileHash":"<hash>","ETag":"<tag>","LastSyncedAt":"<datetime>","LastCheckedAt":"<datetime>","CloudStorageType":0}}</Value>
		</Item>
	</Custom>`

Check if it lists the database you do not want to sync. If so, check if it states "DoNotSync":false.

**Comment by mushak** [comment] 2016-03-03 09:19
No, it does not. It only lists database that I sync. I've just repeated the open/close/restart process a couple of times and these other databases never made it to the configuration file, so I was being asked   after every KeePass restart. They are correctly listed here though:

![image](https://cloud.githubusercontent.com/assets/2347128/13489796/520e2254-e129-11e5-9347-1c6dd1084f54.png)

**Comment by KoenZomers** [comment] 2016-03-07 09:42
Weird. Thanks for providing the details. I'll try to reproduce it on my end.

**Comment by KoenZomers** [comment] 2016-03-30 19:49
Are the "Not in cloud" databases still showing up in the OneDrive Sync Configuration screen after closing KeePass and starting it again?

**Comment by mushak** [comment] 2016-03-30 20:36
No. Only the one that's being synchronized with OneDrive is remembered through restarts. The other ones are not on the list if I start KeePass and just go to OneDriveSync Configuration directly without opening anything.

**Comment by mushak** [comment] 2016-03-30 20:42
I think it might be worth mentioning that I:
- tried it with the latest versions of KeePass 2 as well as the latest version of the OneDriveSync plugin (I use DLLs)
- tried it with all other plugins disabled/removed
- tried it with an entirely new database which does not have any whitespace in its filename (my other databases all have spaces)
- tried it with a new database that does not use the encryption key, only the master password
- tried it with the new database as the only open database

None of it helped.

**Comment by KoenZomers** [comment] 2016-03-31 09:03
Thanks for this valuable information. I managed to reproduce the issue and am working on a fix for it.

**Comment by KoenZomers** [comment] 2016-03-31 09:48
I've localized the cause of the issue and am implementing a fix.

**Comment by KoenZomers** [comment] 2016-03-31 10:26
Released version 1.4.2.0 in which this has been fixed.

**Closed by KoenZomers** 2016-03-31 10:26 UTC
