### ISSUE TITLE
System.ArgumentException: Empty path name is not legal

### ISSUE THREAD

**Issue by easy-peasy** [KoenZomers/KeePassOneDriveSync#23] opened 2016-10-25 13:23 UTC
************\* Exception Text **************
System.ArgumentException: Empty path name is not legal.
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at KeePassLib.Serialization.IOConnection.OpenWrite(IOConnectionInfo ioc)
   at KeePassLib.PwDatabase.Save(IStatusLogger slLogger)
   at KoenZomersKeePassOneDriveSync.KoenZomersKeePassOneDriveSyncExt.<MainWindowOnFileSaved>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll

KeePass
    Assembly Version: 2.34.0.15991
    Win32 Version: 2.34.0.0
##     CodeBase: file:///C:/Users/user/AppData/Local/scoop/apps/keepass/2.34/KeePass.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

KeeOtp
    Assembly Version: 1.3.9.0
    Win32 Version: 1.3.9
##     CodeBase: file:///C:/Users/user/AppData/Local/scoop/apps/keepass/2.34/Plugins/dlls/KeeOtp.dll

KeeAnywhere
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3.0.0
##     CodeBase: file:///C:/Users/user/AppData/Local/KeePass/PluginCache/gsLmfcsTNkrpQnQemTlW/KeeAnywhere.dll

System.Net.Http.Primitives
    Assembly Version: 4.2.29.0
    Win32 Version: 4.2.29.0
##     CodeBase: file:///C:/Users/user/AppData/Local/KeePass/PluginCache/gsLmfcsTNkrpQnQemTlW/System.Net.Http.Primitives.DLL

Newtonsoft.Json
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.3.19514
##     CodeBase: file:///C:/Users/user/AppData/Local/KeePass/PluginCache/gsLmfcsTNkrpQnQemTlW/Newtonsoft.Json.DLL

System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll

System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll

System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll

KoenZomersKeePassOneDriveSync
    Assembly Version: 1.7.1.0
    Win32 Version: 1.7.1.0
##     CodeBase: file:///C:/Users/user/AppData/Local/KeePass/PluginCache/W9xHTm29ilLnImYXad2O/KoenZomersKeePassOneDriveSync.dll

KeePassBrowserImporter
    Assembly Version: 1.0.2.0
    Win32 Version: 1.0.2.0
##     CodeBase: file:///C:/Users/user/AppData/Local/KeePass/PluginCache/yINco5fJyAI4fQ8XiQYO/KeePassBrowserImporter.dll

KeePass.XmlSerializers
    Assembly Version: 2.34.0.15991
    Win32 Version: 2.34.0.15991
##     CodeBase: file:///C:/Users/user/AppData/Local/scoop/apps/keepass/2.34/KeePass.XmlSerializers.DLL

KoenZomers.OneDrive.Api
    Assembly Version: 1.6.6.1
    Win32 Version: 1.6.6.1
##     CodeBase: file:///C:/Users/user/AppData/Local/KeePass/PluginCache/W9xHTm29ilLnImYXad2O/KoenZomers.OneDrive.Api.DLL

System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll

Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

OtpSharp
    Assembly Version: 1.0.5.0
    Win32 Version: 1.0.5.0
##     CodeBase: file:///C:/Users/user/AppData/Local/scoop/apps/keepass/2.34/Plugins/dlls/OtpSharp.DLL

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by KoenZomers** [comment] 2016-10-25 15:12
Can you share the file path where you're saving your database locally?
Is it under the KeePass folder or outside of it?

**Comment by easy-peasy** [comment] 2016-10-25 20:40
Local database is at C:\Users\user\Documents - it is kept outside KeePass folder. KeePass was installed using scoop installer that's why the install path is not under c:\Program Files...

One thing that probably lead to this exception.... KeePass is used on laptop, which at the time was docked (AC power, plus external keyboard, mouse  and most importantly external USB SSD drive). At some point laptop went to sleep mode. I disconnected laptop later without waking it up and ejecting USB SSD drive properly - I was in a rush and I knew there were no open files on USB SSD. Later when I continued using laptop (without USB SSD re-connected) was when the exception occurred. So it is likely this was caused by operator error but nevertheless considering the security nature of KeePass I'd like to see it fixed.

Let me know if you need any further assistance tracking down this problem.

**Comment by easy-peasy** [comment] 2016-10-26 03:38
Actually I was most likely wrong, another exception happened without any external USB SSD drive involvement.

**Comment by KoenZomers** [comment] 2016-11-24 17:29
Can you describe what steps you took before this error showed up? Did you i.e. try to save the database?

**Comment by UserVeryUnknown** [comment] 2017-01-12 10:08
I actually have the same issue, it happens everytime the application autolocks (time based for), when I press 'Coninue' all good (havent tested yet whether the synch is operation or not, cant at the moment)

**Comment by KoenZomers** [comment] 2017-01-15 17:46
Thanks for your research @UserVeryUnknown. The only way for me to reliably match a KeePass database with the additional settings my plugin requires, such as the token to communicate with OneDrive, is by it's physical location. Meaning if you move the KeePass database, like you describe you do, it will see this as a new database, hence will give you the option to sync it and if you do, it will add a new entry in the databases list. This is all by design.

I'm wondering why you move the KeePass database and not just download it to the right place the first time. Could you comment on that?

Are you using a proxy in your corporate environment to access the internet? The plugin uses normal HTTPS / TCP 443 traffic only and should work with most proxies. It could be that you need to play a bit with the KeePass Proxy settings under Tools > Options > Advanced > Proxy to get it to work properly. My plugin takes over these generic KeePass proxy settings automatically.

**Comment by UserVeryUnknown** [comment] 2017-01-17 09:52
Sorry, but I fear you missunderstood something. I did not try to move anything, I just had an existing database sitting on my OneDrive folder, but that file was not written to OneDrive using your plugin (not sure whether that makes a difference), on my home PC I am just reading / writing it to my synched OneDrive folder. Further these were my first attempts with Keepass and the Plugin, so technically, I think we are actually talking about 2 different issues (the proxy issue and the issue opening an existing DB from OneDrive). The proxy issue interferred with it and I first did not recognize that there is an issue with the proxy.

About the proxy issue:
On a side not (only saying this to show it can work), I also tried using Enpass (another Password Manager) and Enpass can sync using the default system proxy settings to connect to OneDrive.
The default system proxy settings is what Keepass is set to. Trying to manually enter them does not fix the issue. When I start of while I am behind the proxy to open a DB from OneDrive, it connects to OneDrive, asks for my credential (on the OneDrive page), asks to confirm the access the app requires and than Keepass creates another exception (see attached File).
[Keepass - Proxy Error One Drive.txt](https://github.com/KoenZomers/KeePassOneDriveSync/files/710560/Keepass.-.Proxy.Error.One.Drive.txt)

**Comment by KoenZomers** [comment] 2017-02-24 09:56
Proxy issues are pretty much impossible for me to troubleshoot as every proxy is different and without access to the proxy, I don't know what is going on. I did set up a Squid Proxy on my end to test proxy scenarios and that worked fine. So it's something specific in the proxy you're using where things bite each other. The OneDrive login page uses the Internet Explorer container component, thus relies on the system proxy settings. Everything my plugin does, such as downloading/uploading/showing the navigation screen all rely on my coding which takes over the proxy configuration from KeePass.

At best what I can do here is ask you for a Fiddler trace when the issue occurs. E-mail it to me and I can try to see if that gives me enough to work with to try to find a resolution for it.

**Comment by KoenZomers** [comment] 2017-05-09 11:33
Closing due to no further response from issue creator.

**Closed by KoenZomers** 2017-05-09 11:33 UTC
