### ISSUE TITLE
Failed to sync database: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by arcmps** [KoenZomers/KeePassOneDriveSync#73] opened 2018-12-04 09:02 UTC
I am sharing a database in One Drive for Business and I am able to add and sync without issue. When any of my colleagues attempt to sync any changes they make to the database, they all receive the following error:

Failed to sync database: Object reference not set to an instance of an object

I have given all of the users 'write' permission. Why does it fail for everyone except me?

KeePass v2.4.0
OneDriveSync 2.0.2.1

Thanks,
 Steve

**Comment by arcmps** [comment] 2018-12-28 23:56
any updates on this ?

**Comment by KoenZomers** [comment] 2019-02-17 20:04
Just tried to reproduce this, but I couldn't get it to fail the way you describe. One thing that I noticed was that when I first shared the KeePass database on my OneDrive for Business with my test account, it did share it but for some weird reason it stopped sharing it again automatically shortly after. Can you double check that the rights are still in place like here:

![image](https://user-images.githubusercontent.com/5940670/52918446-aa93cf00-3329-11e9-92a4-84ebb33f40f9.png)

Can you also confirm that the person you're sharing with has an account in the same Azure Active Directory / Office 365 tenant? Is it a cloud only account or AAD Connec Synced account?

Could you give this a try with the latest plugin version? Just fixed a few issues and released new versions for them. Perhaps as a side effect this issue was also fixed in those versions and that's why I can't reproduce this.

Let me know your findings please.

**Comment by chwba** [comment] 2019-02-17 20:41
+1 KeePass 2.35 on debian 9

**Comment by KoenZomers** [comment] 2019-02-22 17:13
@chwba, can you provide more information on what your scenario is? If it doesn't match the one here, please open a new issue ticket to keep things organised. I'm not aware that my plugin would work on *nix environments. How did you get it to work there?

**Comment by schtritoff** [comment] 2019-02-25 14:23
+1
I think that zhis problem showed up when I switched to "graph API". I had old config but after upgrade to latest KeePassOneDriveSync version I got prompts to login to OneDrive again (this login did not persist between restarts) and then decided to remove config I recreate sync profile. After that I got this error.

**Comment by KoenZomers** [comment] 2019-04-09 21:00
Proxy issues are extremely hard to troubleshoot for me as I don't have a proxy and each proxy behaves differently so if I can't reproduce it, I can't fix it. Have you tried all possible options in the KeePass tool to configure the proxy? Perhaps using one method over another can make a difference?

**Comment by rdolezel** [comment] 2019-05-05 12:28
Let me provide my details of the issue. Another OneDrive user has granted me permissions to her .kdbx file saved on OneDrive (for Consumer).

KeePass 2.42.1, KeePassOneDriveSync 2.0.3.0, W10 Pro 1809 (but I think OS is not so important)
Tested with both MicrosoftGraph and OneDriveConsumer APIs.
The first "Open from OneDrive..." is always successful. Unfortunately any additional attempt to sync ends up with:
"Failed to sync database. Object reference not set to an instance of an object."

I can see the following in OneDriveSync configuration:
Refresh Token Storage: Disk
Last synced with Sun 5 May 2019 12:57:01
Last verified with Sun 5 May 2019 14:16:35

So it seems it successfully downloads a temporary copy to my local disk but then it fails with sync. It seems like it's not a directly OneDrive related issue.

**Comment by KoenZomers** [comment] 2019-05-05 12:31
@rdolezel, not related to the issue discussed here then but let's dive into that. Let me try to reproduce this scenario on my end.

**Comment by KoenZomers** [comment] 2019-05-05 12:38
I can reproduce this one. Let me dive into it to see what's happening.

**Comment by KoenZomers** [comment] 2019-05-05 13:39
Found the issue. It happens if you just share the database with someone, which is of course a perfectly valid scenario. If you share the folder in which the database resides, it works well. Working on a fix.

**Comment by rdolezel** [comment] 2019-05-05 19:18
Interesting. I will try to share the whole folder.

Oh, it really works! Good to know. Easy temporary workaround, thanks for sharing.

**Comment by KoenZomers** [comment] 2019-05-05 19:19
I've fixed the issue. It was quite a difficult one but I managed to do it. Working on releasing a new version now. Will take about an hour to get done.

**Comment by KoenZomers** [comment] 2019-05-05 21:28
Creating the new version also was more complex than I expected, but it has made it. Go ahead and see if with this version it resolves your issue: https://github.com/KoenZomers/KeePassOneDriveSync/releases

**Comment by rdolezel** [comment] 2019-05-05 21:42
New release downloaded and installed, OneDrive folder unshared, OneDrive specific KDBX shared, database opened from "Shared with me" tab.
Trying to Sync now ... works!
Well done, thanks.

**Comment by KoenZomers** [comment] 2019-05-05 22:36
Closing this topic to finish off this discussion. If anyone still needs support on their proxy situation, please open a new issue and be willing to e-mail Fiddler logs to me so I can try to figure out what goes wrong, but it's a bit of a needle in a haystack without being able to reproduce it myself.

**Closed by KoenZomers** 2019-05-05 22:36 UTC
Labels: waiting for more information
