### ISSUE TITLE
SharePoint Online sync create invisible file in sharepoint.

### ISSUE THREAD

**Issue by pholmgren** [KoenZomers/KeePassOneDriveSync#131] opened 2020-05-15 08:15 UTC
**Describe the bug**
I can not see the file on Sharepoint.

**To Reproduce**
1. Open file
2. configure where to sync to
3. Sync with sucsess
4. Go to sharepoint folder and look for file.

**Expected behavior**
a file that syncs to share point suppose to be visible so a new member of SP site can download it.

**Screenshots**
attached screenshot with file missing but sync result successful.
![sharepoint synced file is missing in sharepoint!](https://user-images.githubusercontent.com/10129609/82027673-e6d0ef00-9694-11ea-960c-46f9d40491e6.png)

**Versions (please complete the following information):**
- KeePass [e.g. 2.44]:
- KeePass OneDriveSync Plugin [e.g. 2.1.1.2]:

**Authentication method**
- [X] SharePoint Online

**KeePass database synced with**
- [X] SharePoint Online

**Comment by KoenZomers** [comment] 2020-05-15 10:15
Interesting one. Let me try and see if I can reproduce it.

**Comment by KoenZomers** [comment] 2020-05-16 08:01
Just tried to reproduce it and I cannot get it reproduced. It works for me. Steps I have taken:

1. Create new KeePass database in KeePass
2. Hit CTRL+S to save it and have the plugin ask me if it should sync it -> Yes
3. Go to the SharePoint tab, provide the URL of the SharePoint Online site, i.e. https://tenant.sharepoint.com/sites/mysite, a valid client id and client secret
4. Select location dialog shows, go into Documents library, KeePass folder and then store the database
5. Went to the https://tenant.sharepoint.com/sites/mysite/Shared%20Documents location and saw the KeePass database having been uploaded

Does this match the steps you have taken?

**Comment by pholmgren** [comment] 2020-05-17 12:42
I have tested the above twice with same result = files are hidden from a browser
But I discover that when I did a new test and configured sync I can see the previous files/tests from the plugin where to select a folder!
really strange. 

![strange I can see the hidden files when creating a new sync file](https://user-images.githubusercontent.com/10129609/82146594-b1223680-984b-11ea-8b5d-26c6ff478ce2.png)

Our company sharepoint is in swedish so the link when browsing is https://idnet1.sharepoint.com/sites/IT/Delade%20dokument/ 
when I try with "Shared%20Documents" I get an 404

**Comment by KoenZomers** [comment] 2020-05-18 07:00
Tried it again here on a Dutch and Swedish localized site, and still works:

![image](https://user-images.githubusercontent.com/5940670/82183255-ebd8ad00-98e5-11ea-83b8-b42e0368eb29.png)

Are you not using a modified view in SharePoint which may filter out the KeePass databases? What if you upload other documents through your browser in that same document library, do you see these in the KeePass "Select location" picker? That way we can be 100% sure we're looking at the same location.

**Comment by pholmgren** [comment] 2020-05-19 08:16
I have now tested this and made new word document and uploaded one file.
They did not show in KeePass "Select location" picker but they had a red down arro on the in browser view.
that arrow was telling me they where not "checked in".

After I checked in both files they show up in KeePass "Select location" picker!

So is there same problems with "your" files?
they are not checked in so they are not visible for me as a user.

**Comment by pholmgren** [comment] 2020-05-19 08:23
Its written in Swedish but you can probably translate it ;)

![image](https://user-images.githubusercontent.com/10129609/82302709-42172000-99ba-11ea-8bfc-c0cf3691e3e0.png)

So it looks like that all files created in this folder is marked as "checked out" and are invisible for all other users.

**Comment by KoenZomers** [comment] 2020-05-19 09:10
Interesting findings! So you've got draft versioning on on your library. Can you share with me how these versioning settings look like for you on your library?

![image](https://user-images.githubusercontent.com/5940670/82307887-47c43400-99c1-11ea-8d80-1df1bc67ea84.png)

**Comment by pholmgren** [comment] 2020-05-19 09:41
![image](https://user-images.githubusercontent.com/10129609/82311198-ac818d80-99c5-11ea-9e6e-853d4fcf161f.png)

**Comment by KoenZomers** [comment] 2020-05-21 22:26
Thanks @pholmgren. Key here is the "require documents to be checked out before they can be edited" option. If that's set to Yes, you get the behavior you're experiencing. I can reproduce it now. Let me see if I can do something about this.

**Comment by KoenZomers** [comment] 2020-05-21 23:22
Fixed it. Working on a new release.

**Comment by KoenZomers** [comment] 2020-05-22 00:33
Fixed in [version 2.1.2.0](https://github.com/KoenZomers/KeePassOneDriveSync/releases/tag/2.1.2.0). Closing this issue. Feel free to reopen this issue if it still doesn't work as expected with this new version.

**Closed by KoenZomers** 2020-05-22 00:33 UTC
Labels: investigating
