### ISSUE TITLE
Sync failure when deleting history or icons

### ISSUE THREAD

**Issue by javier-amaya** [KoenZomers/KeePassOneDriveSync#32] opened 2017-08-22 13:07 UTC
Hello,

First of all, thanks for creating a good tool that must be a main part of the KeePass tool, but fourtunatelly you have created that function.

Well, the plugin Works as intended with two exceptions:
- If I delete a copuple of history ítems on an entry, when the entry is replicated, all the deleted entries appear again.
- If I cleanup not used icons, when the sync happens, all of them appear again.

Hope you have some time to check this issues and mey be put some checkbox on the configuration to determine the propper behavior.

Thanks for your good work.

Best regards,

Javier

**Comment by KoenZomers** [comment] 2017-08-22 22:29
Thanks @javier-amaya! The problems you are describing are actually caused by an issue in the KeePass code. There's nothing I can do from my plugin to fix that. The second bullet point has been confirmed by the KeePass maker to be a known issue open since 2009 (no, this is not a typo). I've asked him if the issue you describe at the first bullet point falls under the same umbrella.

You can track me asking this here: https://sourceforge.net/p/keepass/discussion/329221/thread/89feb902/

**Comment by KoenZomers** [comment] 2017-08-23 10:18
As you can see it is confirmed to be "by design" in KeePass. Since 2011 there's an item open to get this changed. The tracking item also mentions a workaround for the first bullet point:

https://sourceforge.net/p/keepass/feature-requests/1463/

Closing this as there's nothing else I can do in this matter unfortunately.

**Closed by KoenZomers** 2017-08-23 10:18 UTC

**Comment by javier-amaya** [comment] 2017-08-23 16:16
Koen, thanks a lot for your answer.
