### ISSUE TITLE
Upload Issue Onedrive Business

### ISSUE THREAD

**Issue by Aconomi** [KoenZomers/KeePassOneDriveSync#88] opened 2019-05-09 12:20 UTC
Hi,

after the first synchronisation of the database, we always get this error:

Failed to sync database: Der Wert darf nicht NULL sein. Parametername: oneDriveUploadSession

Are we doing something wrong?

Greets
Marco

**Comment by KoenZomers** [comment] 2019-05-09 12:35
I've been getting more reports that I may have wrecked something in the very latest version. Can you elaborate a bit more on your scenario so I can hopefully reproduce it and fix it?

1. Are you opening the KeePass database from OneDrive or locally and then syncing it with OneDrive?
2. Are you using Microsoft Graph?
3. Are you storing it on OneDrive consumer or OneDrive for Business?
4. Is the location where it is shared only our own OneDrive or on someone else theirs and just shared with you?
5. Are you storing the refresh token inside the database or on your local file system?

**Comment by Aconomi** [comment] 2019-05-09 12:47
1. Are you opening the KeePass database from OneDrive or locally and then syncing it with OneDrive?
We had the issue with our existing database so we tried some workarounds. We also made a new database c:\users\%username%\documents\filename , imported our old Database (tried kdbx and xml). Saved the DB, upload worked. Made a change, error appears when uploading the file (same with the old and new DB when putting it into Onedrive and opened it with the dialog FILE-->Open from Onedrive).

2. Are you using Microsoft Graph?
Yes we are using Microsoft Graph

3. Are you storing it on OneDrive consumer or OneDrive for Business?
OneDrive for Business

4. Is the location where it is shared only our own OneDrive or on someone else theirs and just shared with you?
Tried both ways, primary it is my own Onedrive but it's shared with my coworkers.

5. Are you storing the refresh token inside the database or on your local file system?
Token is stored inside the DB.

Gonna try the workaround now and give you the information.

**Comment by Aconomi** [comment] 2019-05-09 13:43
Hi,

the older Plugin works.

If you want to try more with the new plugin just ask, we will support you with trying.

Greets

**Comment by KoenZomers** [comment] 2019-05-10 08:34
Still cannot seem to reproduce the issue here. Few more questions:

1. Where on OneDrive for Business are you storing it? In the root or in a folder in the root or in a subfolder of a folder of the root?

2. Are you using an installed version of KeePass or the portable version of KeePass? If installed, did you use the default installation path of C:\Program Files (x86)\KeePass Password Safe 2? If portable, from which path do you run it?

3. Can you elaborate on the "after the first synchronization"? Please provide exact repro steps of just one scenario where it doesn't work. Please don't try to go from I tried this and this and this and none of them worked as that makes it harder for me to find out what exactly you did. I.e. the KeePass database is stored on your local harddrive already, you open it with KeePass, you hit CTRL+S, the plugin dialog pops up asking where to store it, you chose Graph, store in local database, picked a location on your own OneDrive for Business in the <root/folder in the root/subfolder of another folder>, this sync works fine, if I hit CTRL+S again the status bar reports the sync to have failed. Could you write down something like this for me please?

**Comment by LarsMollerEriksen** [comment] 2019-05-14 06:25
Hi Koen

I am experiencing the same issue with OneDrive Personal. Everything works with version 2.0.3.0 of the plugin but reports "Failed to sync database. Value cannot be null. Parameter name: oneDriveUploadSession" every time I save the database with version 2.0.4.0 of the plugin.

I hope it is OK to report my issue in this thread even though it was started as OneDrive for Business.

Please find my answers to the above questions here:
**Remote KeePass Path:** /drive/root:/KeePass/LME.kdbx

**KeePass is installed in:** C:\Program Files (x86)\KeePass Password Safe 2\KeePass.exe

**Plugin is installed in:** C:\Program Files (x86)\KeePass Password Safe 2\Plugins\KeeOneDriveSync\2.0.4.0\KeeOneDriveSync.plgx

**KeePass Version:** 2.42.1

**Cloud Storage Type:** MicrosoftGraph / OneDrive Personal

**OS:** Windows 8.1 x64 and Windows 10 x64. I am running KeePass 2.42.1 on both systems and I experience the same issue on both systems.

**Proxy Server:** No Proxy

Best Regards

Lars

**Comment by KoenZomers** [comment] 2019-05-16 21:46
I've found the issue and am working on a fix

**Comment by KoenZomers** [comment] 2019-05-16 22:41
Issue has been fixed in [version 2.0.4.1](https://github.com/KoenZomers/KeePassOneDriveSync/releases/tag/2.0.4.1)

**Comment by Aconomi** [comment] 2019-05-17 06:30
Hi,

yep it's fixed. Thanks for your work. It is quite faster than the 2.0.3 Plugin.

Great work!!

**Comment by Fulgan** [comment] 2019-05-17 15:28
Hello,

It doesn't seem to be actually fixed: I have the same error with 2.0.4.1 (using OneDriveConsumer).

My DB is local, synched with the one in OneDrive (located in its own sub-directory). I'm using the installed version of keepass 2.42.1 with a default install.

I reverted to 2.0.3 and the issue went away

**Comment by KoenZomers** [comment] 2019-05-17 15:40
Darn it :) Seems like there are more scenarios where it goes wrong then. @Fulgan are you using the Graph API option to sync with your OneDrive consumer? Is your database larger than 5 MB?

**Comment by Fulgan** [comment] 2019-05-18 14:37
No, I'm using the "onedrive" option (on the second tab, IIRC). And yes, my DB is lartger than 5 megs (5191 KB to be precise)

**Comment by KoenZomers** [comment] 2019-05-18 22:02
Very good info. Let me test that scenario. Any reason why you aren't using the Graph option by the way?

**Comment by Fulgan** [comment] 2019-05-19 07:40
I never managed to sucessfully authenticate with it

**Comment by Fulgan** [comment] 2019-05-19 07:40
And once I picked on sync option, I can't seem to change it

**Comment by dgimx** [comment] 2019-05-19 11:05
Hello Koen again (Tom from @ communication). 
I'm following this thread already, so you don't have to send to me emails about this issue :)
As you know, prophylacticaly, I have 2 databases, token in the kdbx file. 
Small (<50kb) and large (9-10mb), small works like a charm, but larger not.  
v2.0.3.0 works very well (on both my databases) but 2.0.4.0 and 2.0.4.1 generated status of the error as above.

**Comment by bbak** [comment] 2019-05-21 09:34
I ran into the same error today. 

Yet in my original setup, I used the Graph API for OneDrive Personal. While playing around I decided to re-initialize the Plugin, but failed because the authentication Popup never allowed me to select my account and always took the Business Account. I'm not sure, if that's really related to this bug.

The only solution was to revert to 2.0.3 AND select the OneDrive Personal as storage provider, since I've never managed to stop the auth-popup to automatically move beyond the view, where I can select or add another account, when using the Graph API.

**Comment by KoenZomers** [comment] 2019-05-22 23:31
I dug into this again tonight. Turns out that the Microsoft OneDrive API is randomly throwing errors when requesting an upload session for uploading larger files. I can fire off the exact same request a couple of times right after each other and some will fail and some will succeed. So this is an issue on the Microsoft side. Having said that, the OneDrive API is deprecated in favor of the Microsoft Graph option by Microsoft. I notice most people running into this issue were still using the OneDrive option. I can't reproduce this when using the Microsoft Graph option. Nevertheless I have built in a lame 5 times retry so when the OneDrive API throws the random error for no reason, then it will automatically retry the upload. In all the tests I have done it has never failed more than five times after each other, so this should mitigate the situation for now. If this workaround kicks in, you will notice in the status bar that it will show attempt #:

![image](https://user-images.githubusercontent.com/5940670/58215480-5cacaf80-7cfa-11e9-917f-accd7fefb47c.png)

The retry will happen automatically and there is nothing you have to do different as an end user than you were doing before.

I will release the new version with this functionality in the next 15 minutes.

**Comment by KoenZomers** [comment] 2019-05-22 23:50
Giving it another try in [version 2.0.4.2](https://github.com/KoenZomers/KeePassOneDriveSync/releases/tag/2.0.4.2) to fix this. Please let me know if you're still experiencing issues with this new version.

**Comment by Fulgan** [comment] 2019-05-23 10:38
As far as I can tell from a couple of tests, the new version works.

There is one thing, however, that I can't understand from your explanation: why does version 2.0.3 work fine when 2.0.4.[0-1] didn't? If it was the result of a server-side issue, I would expect it to fail pretty much in the same way.

I'm not asking just to nitpick but because if it's random, the retrying 3 times might still fail tree time in a row, leading to a potentially unsycronized DB.

Alternative question: I'm willing to switch to graph API (and potentially help with solving the issue I had when I first tried it) but how can I do so with an existing DB?

**Comment by Fulgan** [comment] 2019-05-23 13:09
I switched to GraphAPi (with the new version) and it seems to be working as well

**Comment by bbak** [comment] 2019-05-24 12:05
> I switched to GraphAPi (with the new version) and it seems to be working as well

Same here. Works. Using Graph API and having a private as well as business Account on the machine.

**Comment by KoenZomers** [comment] 2019-05-25 08:55
> As far as I can tell from a couple of tests, the new version works.
> 
> There is one thing, however, that I can't understand from your explanation: why does version 2.0.3 work fine when 2.0.4.[0-1] didn't? If it was the result of a server-side issue, I would expect it to fail pretty much in the same way.
> 
> I'm not asking just to nitpick but because if it's random, the retrying 3 times might still fail tree time in a row, leading to a potentially unsyncronized DB.

Fair question. I did make several changes to the underlying OneDriveApi package over the last year which may play a role in this as I used a new version of it in the KeePass plugin version that started to have issues. The documentation on the OneDrive API has been removed by Microsoft long time ago already to discourage using this old API still and encouraging people to use the Graph API. I also noticed that where the OneDrive for Business, OneDrive Consumer and Graph API always already had slightly different syntaxis for the same command and before these APIs were accepting all three variants on all three making it way easier in my OneDrive API package to support these three without having to code in all the differences for each. Microsoft is updating the services to stick more strict to the specs, being the specific command for each API and no longer having the tolerance for the syntax from the other APIs. This is what I found part of the reason why it stopped working all of a sudden. Part of it was the randomly not working API on the Microsoft side which is why I had a hard time reproducing the issue as I seemed to catch many lucky shots. It could very well be that as a precaution while I was updating some APIs in the OneDrive package that were deviating from their standards, I also updated more of them to meet their standards as described in the API to avoid them stopping to work at some point in time as well. Maybe these new APIs which should be used had the random issue and the old ones didn't, but those would stop working without prior announcement at some point. So it's battling between the evils here, but the solution I have chosen now is most likely to keep working in the future. I'm glad to see everybody report that it's working again for them with this latest update.

I will therefore close this topic for now. If the same problem does show up again, feel free to reopen. Thanks all for sharing your detailed repro steps which helped me to resolve this.

**Closed by KoenZomers** 2019-05-25 08:55 UTC
Labels: bug, investigating, resolved
