### ISSUE TITLE
Opening the same kbdx file in different ways results in two Local Paths

### ISSUE THREAD

**Issue by twistedvibe** [KoenZomers/KeePassOneDriveSync#50] opened 2018-02-02 16:42 UTC
When opening a kbdx file via SharePoint using the File>Open menu works successfully and creates a Local Path in OneDriveSync Options as expected.

Opening the same local file via double clicking in Windows Explorer wants to create a second Local Path in OneDriveSync Options, with just the filename and not the full path. Once opened it errors:

"Failed to sync. Please don't switch to another database before done."

It seems the entries interfere with each other.

I've enclosed a screenshot, hopefully this makes sense.

![keepasssync](https://user-images.githubusercontent.com/6543709/35744341-07d8b93c-0838-11e8-979d-f3072b1d5ab7.jpg)

**Comment by KoenZomers** [comment] 2018-02-02 18:45
Thanks for sharing. Are you using the portable version of KeePass or the installer?

**Comment by twistedvibe** [comment] 2018-02-03 17:57
The installer, latest version of both KeePass and your plugin...

**Comment by KoenZomers** [comment] 2018-04-29 13:38
I can reproduce it. Will investigate where it goes wrong.

**Comment by rangerxusa** [comment] 2018-05-17 04:49
I like your plugin for syncing with onedrive. I too encounter problems with multiple entries in the config form and sync errors. I downloaded your code and tried to find the problem. NOTE: The source you posted under releases with the 2.0.2.0 plugin is actually code 2.0.1.2 so I wasted some time debugging the wrong code.
You had already seen that using Environment.Currentdirectoy was a problem as it is not the application folder but the working directory. When using KeePass option to run at startup the system uses c:\windows\system32 which broke your code. I changed the reference to use Application.StartupPath which fixed some problems. But there were still errors in the Configuration form display and when syncing getting "Please don't switch to another database before done". 
Looking at the code further it seems there are a lot of methods that expect the full path and do not have the code to expand the relative path to the full path. I started to change the code but decided there were way to many places that needed to be changed.
I assume you use the relative patch for portable users so they can store their database in the KeePass folder and no matter where the portable KeePass is loaded it can use the existing settings for syncing. I decided to remove the relative path code from the plugin. There were four places 1) KoenZomersKeePassOneDriveSyncExt.cs KeePassDatabaseOpened, KoenZomersKeePassOneDriveSyncExt.cs MainWindowOnFileSaved, and OneDriveProvide.cs & SharePointProvder.cs (both after IF statement after comment "Ensure the database that needs to be synced is still the database currently selected"). After recompile I have had no problems with duplicate paths in the Configuration form or error message when syncing.
It seemed to me instead of recoding many places to support relative paths it would be better to always store the full patch and do a test when opening a database. In Configuration.cs GetPasswordDatabaseConfiguration change code as follows: 1) If database not found then get the DB name to open and FOREACH the configuration.keys and see it it already exists with another path. If true and it's folder path contains the folder (not full path) of the keepass.exe then assume it is one and the same. Since you can't change the configuration.key add a new configuration entry with the new path + DB Name as key and old path's configuration.value and then delete the entire configuration entry of the old path. Now you have the full path and all your code will work. You need to  to do a similar check and switch in the OneDriveConfigForm.cs so the form doesn't show database not found. I don't think there are other places that would need to be changed.
I started to make the above code changes but have ran out of time. I thought I would pass these thoughts on to you in case they are of any value.

**Comment by KoenZomers** [comment] 2019-07-07 19:29
Thanks @rangerxusa for sharing your findings. I actually didn't notice them until now, which is more than a year later. Sorry for that. I have made attempts to make changes in this area as well and ran against the same challenge: the path is so tied in all the code that it will likely cause a lot of issues if I try to change it all to relative paths. I started on attempts to do so and after some hours decided to not go for it. Maybe in the future I will make another attempt. For now I'll close this issue as the issue for which this thread was opened has been resolved a while ago already.

**Closed by KoenZomers** 2019-07-07 19:29 UTC
